query elections{
    pendingElections{
        start
      	end
      	description
        id
    }
}

query electoralProcesses{
  electoralProcesses{
      __typename
  ... on Election{
    id
    description
  }
  ... on Poll{
    id
    description
  }
  }

}

query options($id: ID!) {
  election(id: $id) {
    start
    end
    description
    candidates {
      id
      firstName
      lastName
    }
  }
}

query census($id: ID!) {
  election(id: $id) {
    description
    start
    end
    censuses {
      voters {
        firstName
        lastName
      }
    }
  }
}

query PastElectionResults {
  electoralProcesses(finished: true) {
    __typename
    ... on Election {
      id
      description
      start
      end
    }
    ... on Poll {
      id
      description
      start
      end
    }
  }
}

mutation votePoll($input: VotePollInput!) {
  voteOnPoll(input: $input)
}