query elections {
  pendingElections {
    start
    end
    description
    id
  }
}

query polls {
  polls {
    id
    start
    end
    description
  }
}

query electoralProcesses {
  pendingElectoralProcesses {
    __typename
    ... on Election {
      id
      description
      start
      end
    }
    ... on Poll {
      id
      description
      start
      end
    }
  }
}

query options($id: ID!) {
  poll(id: $id) {
    start
    end
    description
    options {
      id
      text
    }
  }
}

query census($id: ID!) {
  electoralProcess(id: $id) {
    __typename
    ... on Election {
    description
    start
    end
    secretary {
      firstName
      lastName
    }
    censuses {
      voters {
        firstName
        lastName
      }
    }
    delegates {
      firstName
      lastName
    }
    }

    __typename
    ... on Poll {
      description
      start
      end
      secretary {
        firstName
        lastName
      }
      censuses {
        voters {
          firstName
          lastName
        }
      }
      delegates {
        firstName
        lastName
      }
    }
  }
}

query PastElectionResults {
  electoralProcesses(finished: true) {
    __typename
    ... on Election {
      id
      description
      start
      end
    }
    ... on Poll {
      id
      description
      start
      end
    }
  }
}

mutation deleteElection($id: ID!) {
  deleteElection(id: $id)
}

mutation deletePoll($id: ID!) {
  deletePoll(id: $id)
}

query getElectoralProcess($id: ID!) {
  electoralProcess(id: $id) {
    __typename
    ... on Election {
      id
      description
      start
      end
    }
    ... on Poll {
      id
      description
      start
      end
    }
  }
}

query colegios {
  collegiateBodies {
    id
    name
  }
  users {
    id
    firstName
    lastName
    colegiateBody {
      id
    }
  }
}

mutation deleteElectoralProcess(
  $id: ID!
  $poll: Boolean!
  $election: Boolean!
) {
  deletePoll(id: $id) @include(if: $poll)
  deleteElection(id: $id) @include(if: $election)
}

query optionsElection($id: ID!) {
  election(id: $id) {
    start
    end
    description
    candidates {
      id
      firstName
      lastName
    }
  }
}
